### ISSUE TITLE
Documentation of Customer Meeting #1

### ISSUE THREAD

**Issue by yaman-kindap** [bounswe/bounswe2018group8#12]
Please update the wiki page with your notes.

**Comment by selim-karaduman** [comment]
The asnwers that i noted in the meeting are:

- A client can post his project as public or privat
- Use API for tag semantic. One such API is [WikiData]https://www.wikidata.org/wiki/Wikidata:Main_Pagel)
- Make the chat using database. It is not going to be instant chat that uses sockets.
- Only the client can see the bids offered to him


Those are the ones that i had noted down.If there are any mistakes please correct them.
