### ISSUE TITLE
Requirements Feedback

### ISSUE THREAD

**Issue by selim-karaduman** [bounswe/bounswe2018group8#15]
Hello friends,
This is the feedback we have got : https://piazza.com/class/jd5vcsniag3zz?cid=37

As stated in the text , the things-to-do are:

- There should be a glossary part at the beginning of the requirements
- Putting Functional requirements above non-functional requirements
- Distinguishing the requirements about guests, freelancers and clients
- And so on.

So, i think we should take care of these as soon as possible.

**Comment by ismet-dagli** [comment]
The requirements part is fixed by @selim-karaduman according to the feedback that has already given by @cihatbaktir. After that, @abdullah-coskun and me examined again and revised a couple tiny points.
