### ISSUE TITLE
Quality Assurance - Acceptance test

### ISSUE THREAD

**Issue by ismet-dagli** [bounswe/bounswe2018group8#32]
You should get your mind into the specific input/output relationships of your use cases and design how your system should perform 

Here are the example links: 

[https://piazza.com/class_profile/get_resource/jd5vcsniag3zz/jf7rh1j3m0m6t2](url)
[http://www.guru99.com/test-case.html](url)
[http://www.softwaretestinghelp.com/sample-test-cases-testing-web-desktop-applications/](url)

**Comment by KubraE** [comment]
I think the links are broken, can you take a look? @ismet-dagli

**Comment by ismet-dagli** [comment]
The first version of test case are done.
