### ISSUE TITLE
Create annotation related scenarios

### ISSUE THREAD

**Issue by mehmetcalim** [bounswe/bounswe2018group8#38]
Add 3 annotation related user scenarios to User Personas and Scenarios section of wiki page.

**Comment by mehmetcalim** [comment]
I added one of the annotation related scenarios. [https://github.com/bounswe/bounswe2018group8/wiki/User-Personas-and-Scenarios](url)

**Comment by leblebi1** [comment]
I added one of the annotation related scenarios, with the name "Pelinsu Tuncer". [Page:](https://github.com/bounswe/bounswe2018group8/wiki/User-Personas-and-Scenarios)

**Comment by semih-ari** [comment]
I added one  annotation related scenario with the name "Alex de Souza". https://github.com/bounswe/bounswe2018group8/issues/38#issuecomment-427485571
