### ISSUE TITLE
Project endpoints need to be fixed

### ISSUE THREAD

**Issue by umutoztunc** [bounswe/bounswe2018group8#55]
After I have seperated project related code into a project app, I have edited some of the endpoints. The endpoints and views must be fixed. Let me clarify the expected endpoints and their respective behaviour.

```
GET /projects/ : List all the projects.
POST /projects/ : Create new project.
GET /projects/<id>/ : Retrieve the project with the given id.
PUT /projects/<id>/ : Update the project with the given id.
PATCH /projects/<id>/ Partial update the project with the given id.
DELETE /projects/<id>/ : Delete the project with the given id. 
```

If you have any questions or suggestions about the endpoints and their purposes, just let me know.

**Comment by ozanknskl** [comment]
Endpoints are fixed.
