### ISSUE TITLE
Bug about project owner name at home page

### ISSUE THREAD

**Issue by KubraE** [bounswe/bounswe2018group8#60]
At the home page, the project owners name is blinking and switching rapidly. It needs to be fixed asap.

**Comment by mehmetcalim** [comment]
We are working on it with backend team. This bug will be fixed by adding username field to projects endpoint and changing frontend according to this change.

**Comment by ozanknskl** [comment]
@mehmetcalim I added the 'owner' field in the backend, so when you change the frontend part you can close the issue.

**Comment by umutoztunc** [comment]
I have modified the fields such that you can retrieve the client information as client_id and client_username. Same applies to the freelancer related information.

**Comment by mehmetcalim** [comment]
After modified backend side, I fixed this bug and now owner names of projects seem properly.
