### ISSUE TITLE
Questions for Customer Meeting 

### ISSUE THREAD

**Issue by KubraE** [bounswe/bounswe2018group8#7]
We have our first customer meeting so we need to be prepared! Every team member should post at least one question to the .doc file until meeting. I sent the URL for the .doc file via e-mail.

**Comment by abdullah-coskun** [comment]
What should be the quota for a client or a free lancer to be considered as reliable?
What should be punishment for intentionally doing a bad job besides rating and how can we solve an argument between free lancer and client?

**Comment by KubraE** [comment]
@abdullah-coskun For the first question : "it is up to the client".
The second is answered by the customer.
