### ISSUE TITLE
Bid average is shown as zero in frontend and android.

### ISSUE THREAD

**Issue by umutoztunc** [bounswe/bounswe2018group8#81]
Our frontend and mobil application interface shows average bid as $0.0 for a project with no bids have been made yet. We know that people are not allowed to make non-positive bids. Therefore, it is not logical to say that project's average bid is $0.0. Instead, we can simply say that "No bids have been made for this project yet."

**Comment by leblebi1** [comment]
I just fixed and commited the Android part.

**Comment by mehmetcalim** [comment]
It is fixed at both sides.
